name: Install New Relic Infrastructure Agent on EC2 instance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EC2_INSTANCE_ID: i-05510310afb9021e2
  NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}

jobs:
  install-nr-agent:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Get Instance IP
      id: get-instance-ip
      run: |
        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
        echo "::set-output name=instance_ip::$INSTANCE_IP"
    - name: Install New Relic Infrastructure Agent
      run: |
        curl -L https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | sudo apt-key add -
        printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/newrelic-infra.list
        sudo apt-get update
        sudo apt-get install newrelic-infra -y
      env:
        NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}
    - name: Configure New Relic Infrastructure Agent
      run: |
        sudo sed -i "s/^license_key:.*/license_key: $NR_LICENSE_KEY/" /etc/newrelic-infra.yml
        sudo sed -i "s/^hostname:.*/hostname: ${{ steps.get-instance-ip.outputs.instance_ip }}/" /etc/newrelic-infra.yml
      env:
        NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}
