name: Install New Relic Infrastructure Agent on EC2 instance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EC2_INSTANCE_ID: i-05510310afb9021e2
  NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}

jobs:
  install-nr-agent:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Install New Relic agent
      env:
        NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      run: |
        echo "deb http://apt.newrelic.com/debian/ newrelic non-free" | sudo tee /etc/apt/sources.list.d/newrelic.list
        wget -O- https://download.newrelic.com/548C16BF.gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install newrelic-sysmond -y
        sudo nrsysmond-config --set license_key=${NR_LICENSE_KEY}
        sudo service newrelic-sysmond start
    - name: Configure New Relic agent
      env:
        NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      run: |
        echo "license_key: ${NEW_RELIC_LICENSE_KEY}" | sudo tee -a /etc/newrelic-infra.yml
        sudo systemctl restart newrelic-infra


# this way is also working but there is a error
